-- MySQL Script generated by MySQL Workbench
-- Sat Sep  4 17:26:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema manager_phone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manager_phone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manager_phone` DEFAULT CHARACTER SET latin1 ;
USE `manager_phone` ;

-- -----------------------------------------------------
-- Table `manager_phone`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`accounts` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `fullname` VARCHAR(25) NULL DEFAULT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `bod` DATETIME NULL DEFAULT NULL,
  `lastlogindate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`category` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`customer` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `gmail` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`deliverer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`deliverer` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`orderstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`orderstatus` (
  `id` INT(11) NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`orders` (
  `id` INT(11) NOT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `total_price` INT(11) NULL DEFAULT NULL,
  `delivery_address` VARCHAR(255) NULL DEFAULT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `orderstatus_id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `deliverer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`roles` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`accountcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`accountcard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accounts_id` INT(11) NOT NULL,
  `roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager_phone`.`productphones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`productphones` (
  `id` INT(11) NOT NULL,
  `name_phone` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `decription` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `original_price` DOUBLE NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `size` VARCHAR(255) NULL DEFAULT NULL,
  `weight` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `memory` VARCHAR(255) NULL DEFAULT NULL,
  `os` VARCHAR(255) NULL DEFAULT NULL,
  `cpu_speed` VARCHAR(255) NULL DEFAULT NULL,
  `camera_primary` VARCHAR(255) NULL DEFAULT NULL,
  `camera_secondary` VARCHAR(255) NULL DEFAULT NULL,
  `battery` VARCHAR(255) NULL DEFAULT NULL,
  `warranty` VARCHAR(255) NULL DEFAULT NULL,
  `bluetooth` VARCHAR(255) NULL DEFAULT NULL,
  `wlan` VARCHAR(255) NULL DEFAULT NULL,
  `promotion_price` INT(12) NULL DEFAULT NULL,
  `start_promotion` DATETIME NULL DEFAULT NULL,
  `end_promotion` DATETIME NULL DEFAULT NULL,
  `date_areated` DATETIME NULL,
  `category_id` INT(11) NOT NULL,
  `accountcard_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`orderdetails` (
  `id` INT(11) NOT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `sale_quantity` INT(11) NULL DEFAULT NULL,
  `orders_id` INT(11) NOT NULL,
  `productphones_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`salephones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`salephones` (
  `id` INT(11) NOT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `productphones_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `manager_phone`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `price` DOUBLE NULL,
  `productphones_id` INT(11) NOT NULL,
  `accountcard_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager_phone`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_phone`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NULL,
  `amount` INT NULL,
  `fee` DOUBLE NULL,
  `message` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(50) NULL,
  `address` VARCHAR(255) NULL,
  `active` TINYINT(5) NULL,
  `created_at` DATETIME NULL,
  `deliverer_id` INT(11) NOT NULL,
  `cart_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `manager_phone`.`accounts`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`accounts` (`id`, `username`, `password`, `fullname`, `phone`, `email`, `bod`, `lastlogindate`) VALUES (0, 'anhict', 'kevinanh9x', 'Nguyen The Anh', '038613031', 'theanh4497@gmail.com', '1997/04/04', '2021/09/04');
INSERT INTO `manager_phone`.`accounts` (`id`, `username`, `password`, `fullname`, `phone`, `email`, `bod`, `lastlogindate`) VALUES (1, 'thucanh', 'thucanh98', 'Hoang Thuc Anh', '038645448', 'thucanh98@gmail.com', '1998/06/06', '2021/09/04');
INSERT INTO `manager_phone`.`accounts` (`id`, `username`, `password`, `fullname`, `phone`, `email`, `bod`, `lastlogindate`) VALUES (2, 'sontran', 'sontran93', 'Tran Van Son', '035567845', 'sontran93@gmail.com', '1993/05/11', '2021/09/04');
INSERT INTO `manager_phone`.`accounts` (`id`, `username`, `password`, `fullname`, `phone`, `email`, `bod`, `lastlogindate`) VALUES (3, 'hanhvu', 'vuhanh', 'Vu Hanh', '034562656', 'vuhanh357@gmail.com', '1984/06/22', '2021/09/04');
INSERT INTO `manager_phone`.`accounts` (`id`, `username`, `password`, `fullname`, `phone`, `email`, `bod`, `lastlogindate`) VALUES (4, 'congvinh', 'vinhcong69', 'Truong Gia Cong Vinh', '038664347', 'vinhcong921@gmail.com', '1991/06/08', '2021/09/04');
INSERT INTO `manager_phone`.`accounts` (`id`, `username`, `password`, `fullname`, `phone`, `email`, `bod`, `lastlogindate`) VALUES (5, 'dangninh', 'dangninh66', 'Dang Van Ninh', '037654616', 'dangninh@gmail.com', '1992/11/06', '2021/09/04');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`category` (`id`, `name`, `parent_id`) VALUES (0, 'IPhone', 0);
INSERT INTO `manager_phone`.`category` (`id`, `name`, `parent_id`) VALUES (1, 'Samsung', 1);
INSERT INTO `manager_phone`.`category` (`id`, `name`, `parent_id`) VALUES (2, 'Oppo', 2);
INSERT INTO `manager_phone`.`category` (`id`, `name`, `parent_id`) VALUES (3, 'remmi', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`customer` (`id`, `name`, `phone`, `gmail`) VALUES (0, 'Nguyen The Anh', '0386130391', 'theanh4497@gmail.com');
INSERT INTO `manager_phone`.`customer` (`id`, `name`, `phone`, `gmail`) VALUES (1, 'Hoang Thuc Anh', '038645448', 'thucanh98@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`deliverer`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`deliverer` (`id`, `name`, `phone`) VALUES (0, 'Nguyen The Anh', '0386130391');
INSERT INTO `manager_phone`.`deliverer` (`id`, `name`, `phone`) VALUES (1, 'Hoang Thuc Anh', '038645448');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`orderstatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`orderstatus` (`id`, `status`) VALUES (0, 'đã đặt hàng');
INSERT INTO `manager_phone`.`orderstatus` (`id`, `status`) VALUES (1, 'đẵ thêm vào gỏ hàng');
INSERT INTO `manager_phone`.`orderstatus` (`id`, `status`) VALUES (2, 'Chưa đặt hàng');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`orders`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`orders` (`id`, `create_date`, `total_price`, `delivery_address`, `note`, `orderstatus_id`, `customer_id`, `deliverer_id`) VALUES (0, '2021/08/04', 6, 'Ta Thanh oai- Thanh Tri - HN', 'da mua', 0, 0, 0);
INSERT INTO `manager_phone`.`orders` (`id`, `create_date`, `total_price`, `delivery_address`, `note`, `orderstatus_id`, `customer_id`, `deliverer_id`) VALUES (1, '2021/08/09', 4, 'Ngu Hiep', 'da thanh toan', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`roles` (`id`, `name`, `phone`, `description`) VALUES (0, 'Nguyen The Anh', '0386130391', 'admin');
INSERT INTO `manager_phone`.`roles` (`id`, `name`, `phone`, `description`) VALUES (1, 'Hoang Thuc Anh', '038645448', 'admin');
INSERT INTO `manager_phone`.`roles` (`id`, `name`, `phone`, `description`) VALUES (2, 'Tran Van Son', '035567845', 'user');
INSERT INTO `manager_phone`.`roles` (`id`, `name`, `phone`, `description`) VALUES (3, 'Vu Hanh', '034562656', 'user');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`accountcard`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`accountcard` (`id`, `accounts_id`, `roles_id`) VALUES (0, 0, 0);
INSERT INTO `manager_phone`.`accountcard` (`id`, `accounts_id`, `roles_id`) VALUES (1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`productphones`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`productphones` (`id`, `name_phone`, `title`, `decription`, `price`, `original_price`, `quantity`, `size`, `weight`, `color`, `image`, `memory`, `os`, `cpu_speed`, `camera_primary`, `camera_secondary`, `battery`, `warranty`, `bluetooth`, `wlan`, `promotion_price`, `start_promotion`, `end_promotion`, `date_areated`, `category_id`, `accountcard_id`) VALUES (0, 'Iphone 5s', 'Iphone 5s', 'Iphone 5s phiên bản trăng', 1500000, 3000000, 12, 'nhỏ', '52kg', 'trang', 'iphone5s.png', '1 GB', 'IOS', '5GHZ', '5px', '12px', '5000', 'pin salpin', '2.0', '6hz', 1000000, '2021/08/04', '2021/08/10', '2021/03/06', 0, 1);
INSERT INTO `manager_phone`.`productphones` (`id`, `name_phone`, `title`, `decription`, `price`, `original_price`, `quantity`, `size`, `weight`, `color`, `image`, `memory`, `os`, `cpu_speed`, `camera_primary`, `camera_secondary`, `battery`, `warranty`, `bluetooth`, `wlan`, `promotion_price`, `start_promotion`, `end_promotion`, `date_areated`, `category_id`, `accountcard_id`) VALUES (1, 'Galaxy S21', 'SamSung', 'SamSung phien ban moi', 200000000, 25000000, 50, 'lớn', '62kg', 'xanh', 'galaxy-21.png', '126GB', 'Android', '12Gz', '12px', '20px', '6000', 'pin salea', '5.0', '45hz', 15000000, '2021/08/06', '2021/08/12', '2021/03/11', 1, 0);
INSERT INTO `manager_phone`.`productphones` (`id`, `name_phone`, `title`, `decription`, `price`, `original_price`, `quantity`, `size`, `weight`, `color`, `image`, `memory`, `os`, `cpu_speed`, `camera_primary`, `camera_secondary`, `battery`, `warranty`, `bluetooth`, `wlan`, `promotion_price`, `start_promotion`, `end_promotion`, `date_areated`, `category_id`, `accountcard_id`) VALUES (2, 'Remi8', 'xiaomi Remi8', 'xiaomi Remi8 phiên bản tai thỏ', 5000000, 9000000, 30, 'vừa', '45kg', 'den', 'remi8.png', '12GB', 'Android', '8GZ', '5px', '8px', '5000', 'phim delas', '4.0', '25hz', 4300000, '2021/08/04', '2021/08/11', '2021/03/12', 3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`orderdetails`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`orderdetails` (`id`, `price`, `sale_quantity`, `orders_id`, `productphones_id`) VALUES (0, 5000000, 5, 1, 0);
INSERT INTO `manager_phone`.`orderdetails` (`id`, `price`, `sale_quantity`, `orders_id`, `productphones_id`) VALUES (1, 100000000, 10, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`salephones`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`salephones` (`id`, `quantity`, `create_date`, `productphones_id`) VALUES (0, 10, '2021/08/03', 0);
INSERT INTO `manager_phone`.`salephones` (`id`, `quantity`, `create_date`, `productphones_id`) VALUES (1, 15, '2021/08/04', 1);
INSERT INTO `manager_phone`.`salephones` (`id`, `quantity`, `create_date`, `productphones_id`) VALUES (2, 6, '2021/08/02', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`cart`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`cart` (`id`, `quantity`, `price`, `productphones_id`, `accountcard_id`) VALUES (0, 5, 15000000, 1, 2);
INSERT INTO `manager_phone`.`cart` (`id`, `quantity`, `price`, `productphones_id`, `accountcard_id`) VALUES (1, 6, 200000000, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manager_phone`.`transactions`
-- -----------------------------------------------------
START TRANSACTION;
USE `manager_phone`;
INSERT INTO `manager_phone`.`transactions` (`id`, `transaction_date`, `amount`, `fee`, `message`, `name`, `phone`, `email`, `address`, `active`, `created_at`, `deliverer_id`, `cart_id`) VALUES (0, '2021/06/20', 5, 5000000, 'da thanh toan', 'Nguyen The Anh', '0386130391', 'theanh4497@gmail.com', 'Ta Thanh Oai- Thanh Tri- Ha Noi', 1, '2021/06/11', 0, 0);
INSERT INTO `manager_phone`.`transactions` (`id`, `transaction_date`, `amount`, `fee`, `message`, `name`, `phone`, `email`, `address`, `active`, `created_at`, `deliverer_id`, `cart_id`) VALUES (1, '2021/06/21', 6, 6000000, 'da thanh toan', 'Hoang Thuc Anh', '038645448', 'thucanh98@gmail.com', 'Ngu Hiep', 2, '2021/06/12', 1, 1);

COMMIT;

